language: python
install: pip install tox
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py26
    - python: 2.7
      env: TOX_ENV=py27
    - python: 2.7
      env: TOX_ENV=py33
    - python: 2.7
      env: TOX_ENV=py34
    - python: 2.7
      env: TOX_ENV=pypy
    - python: 2.7
      env: TOX_ENV=flake8
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6-dev
      env: TOX_ENV=py36
script:
    - tox -e $TOX_ENV
services:
  - mongodb
  - redis-server
before_script:
    # timer is needed in order to get mongo to properly initialize on travis-ci
    # See https://github.com/travis-ci/travis-ci/issues/1967#issuecomment-42008605
  - sleep 15
  - mongo eve_test --eval 'db.addUser("test_user", "test_pw");'
