name: Release Wheel

on: [push, pull_request]

jobs:
 build_wheel:
    name: "Build wheel"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build wheels
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          quay.io/pypa/manylinux2014_x86_64 \
          bash -exc '/opt/python/cp38-cp38/bin/python -m pip install wheel && \
          /opt/python/cp38-cp38/bin/python -m pip wheel -w ./wheelhouse/ .'
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
       path: ./wheelhouse/Eve-*.whl
       name: dist

 deploy:

    runs-on: ubuntu-latest
    needs: build_wheel
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v2
      - name: Download distributions
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
